apiVersion: apps/v1
kind: Deployment
metadata:
  name: historial-api
  labels:
    app: historial-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historial-api
  template:
    metadata:
      labels:
        app: historial-api
    spec:
      containers:
      - name: historial-api
        image: localhost/historial-api:0.1
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: historial-api-config
        - secretRef:
            name: historial-api-secrets
