apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-historial-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
